### ISSUE TITLE
Add query param values to widget definitions

### ISSUE THREAD

**Issue by tombakerjr** [netuitive-community-packages/netuitive-packages-total-cost#3]
The UI has been updated to look for certain attributes on the widget and use them to add query params to the "Go to Report" links. Those fields need to be added to the widget definitions in this package.

**Comment by TheConnMan** [comment]
Which query params should be added?

**Comment by TheConnMan** [comment]
This has already been done in https://github.com/netuitive-community-packages/netuitive-packages-aws-cost/commit/a1a0c4e8c71855ab87d28d8501c79dcb856810aa.

The query params were `grouping` and `topNLimit`.
